// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ4iXeMY38FzP0xrbPtrfoQ_WOHztRPtY',
    appId: '1:34035996335:web:fa4f62977b9458acd1e65a',
    messagingSenderId: '34035996335',
    projectId: 'gerenciador-cadastro-senai',
    authDomain: 'gerenciador-cadastro-senai.firebaseapp.com',
    storageBucket: 'gerenciador-cadastro-senai.firebasestorage.app',
    measurementId: 'G-WKZFVYWMCV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU-rihSCFs3PpotCuhSBrI23GMhhrQEVs',
    appId: '1:34035996335:android:dddde21f3279ba30d1e65a',
    messagingSenderId: '34035996335',
    projectId: 'gerenciador-cadastro-senai',
    storageBucket: 'gerenciador-cadastro-senai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8iK9W9VmTNATK10pQv8o3NLr6R6veOvs',
    appId: '1:34035996335:ios:d1ee3c1cc9a4ab49d1e65a',
    messagingSenderId: '34035996335',
    projectId: 'gerenciador-cadastro-senai',
    storageBucket: 'gerenciador-cadastro-senai.firebasestorage.app',
    iosBundleId: 'com.example.gerenciadorClientes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8iK9W9VmTNATK10pQv8o3NLr6R6veOvs',
    appId: '1:34035996335:ios:d1ee3c1cc9a4ab49d1e65a',
    messagingSenderId: '34035996335',
    projectId: 'gerenciador-cadastro-senai',
    storageBucket: 'gerenciador-cadastro-senai.firebasestorage.app',
    iosBundleId: 'com.example.gerenciadorClientes',
  );
}
